---
title: Nathaniel Ward
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Nathaniel Ward is an online marketer and fundraiser in Washington, DC.
baseurl: 
url: https://www.nathanielward.net
permalink: "/:year/:month/:title"
future: false
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
- jekyll-paginate
