# Site settings
title: Nathaniel Ward
description: Nathaniel Ward is an online marketer and fundraiser in Washington, DC.
baseurl: ""
url: http://www.nathanielward.net

# Build settings
markdown: kramdown
