# Site settings
title: Nathaniel Ward
description: Nathaniel Ward is an online marketer and fundraiser in Washington, DC.
baseurl: ""
url: http://www.nathanielward.net

# Build settings
permalink: /:year/:month/:title
timezone: America/New_York
paginate: 5
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed