# Site settings
title: Nathaniel Ward
description: Nathaniel Ward is an online marketer and fundraiser in Washington, DC.
baseurl: ""
url: https://www.nathanielward.net

# Build settings
permalink: "/:year/:month/:title"
future: false
timezone: America/New_York
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed
    
    
# Gems
gems: [jekyll-paginate]